#!/bin/bash
Secret="secret_#####"
Databaseid="#####"
Groupe=$(echo "$1")
Titre=$(echo "$2")
Status=$(echo "$3")
curl -s -X POST https://api.notion.com/v1/pages -H "Authorization: Bearer ${Secret}" -H "Content-Type: application/json" -H "Notion-Version: 2021-05-13" --data '{"parent": { "database_id": "'${Databaseid}'" }, "properties": {"title": {"title": [{"text": {"content": "'"${Titre}"'"}}]},"Groupe": {"multi_select": [{"name": "'"${Groupe}"'"}]},"Status": {"multi_select": [{"name": "'"${Status}"'"}]}}}'
